/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: callback.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "callback.pb-c.h"
void   agoracallback__tconnection_info__init
                     (Agoracallback__TConnectionInfo         *message)
{
  static const Agoracallback__TConnectionInfo init_value = AGORACALLBACK__TCONNECTION_INFO__INIT;
  *message = init_value;
}
size_t agoracallback__tconnection_info__get_packed_size
                     (const Agoracallback__TConnectionInfo *message)
{
  assert(message->base.descriptor == &agoracallback__tconnection_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t agoracallback__tconnection_info__pack
                     (const Agoracallback__TConnectionInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &agoracallback__tconnection_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t agoracallback__tconnection_info__pack_to_buffer
                     (const Agoracallback__TConnectionInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &agoracallback__tconnection_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Agoracallback__TConnectionInfo *
       agoracallback__tconnection_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Agoracallback__TConnectionInfo *)
     protobuf_c_message_unpack (&agoracallback__tconnection_info__descriptor,
                                allocator, len, data);
}
void   agoracallback__tconnection_info__free_unpacked
                     (Agoracallback__TConnectionInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &agoracallback__tconnection_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor agoracallback__tconnection_info__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "channelId",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, channelid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "localUserId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, localuserid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "internalUid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, internaluid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proxyType",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, proxytype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectionIp",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Agoracallback__TConnectionInfo, connectionip),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned agoracallback__tconnection_info__field_indices_by_name[] = {
  1,   /* field[1] = channelId */
  6,   /* field[6] = connectionIp */
  0,   /* field[0] = id */
  4,   /* field[4] = internalUid */
  3,   /* field[3] = localUserId */
  5,   /* field[5] = proxyType */
  2,   /* field[2] = state */
};
static const ProtobufCIntRange agoracallback__tconnection_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor agoracallback__tconnection_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "agoracallback.TConnectionInfo",
  "TConnectionInfo",
  "Agoracallback__TConnectionInfo",
  "agoracallback",
  sizeof(Agoracallback__TConnectionInfo),
  7,
  agoracallback__tconnection_info__field_descriptors,
  agoracallback__tconnection_info__field_indices_by_name,
  1,  agoracallback__tconnection_info__number_ranges,
  (ProtobufCMessageInit) agoracallback__tconnection_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
