/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: callback.proto */

#ifndef PROTOBUF_C_callback_2eproto__INCLUDED
#define PROTOBUF_C_callback_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Agoracallback__TConnectionInfo Agoracallback__TConnectionInfo;


/* --- enums --- */


/* --- messages --- */

struct  _Agoracallback__TConnectionInfo
{
  ProtobufCMessage base;
  int32_t id;
  char *channelid;
  int32_t state;
  char *localuserid;
  int32_t internaluid;
  int32_t proxytype;
  char *connectionip;
};
#define AGORACALLBACK__TCONNECTION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&agoracallback__tconnection_info__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string }


/* Agoracallback__TConnectionInfo methods */
void   agoracallback__tconnection_info__init
                     (Agoracallback__TConnectionInfo         *message);
size_t agoracallback__tconnection_info__get_packed_size
                     (const Agoracallback__TConnectionInfo   *message);
size_t agoracallback__tconnection_info__pack
                     (const Agoracallback__TConnectionInfo   *message,
                      uint8_t             *out);
size_t agoracallback__tconnection_info__pack_to_buffer
                     (const Agoracallback__TConnectionInfo   *message,
                      ProtobufCBuffer     *buffer);
Agoracallback__TConnectionInfo *
       agoracallback__tconnection_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   agoracallback__tconnection_info__free_unpacked
                     (Agoracallback__TConnectionInfo *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Agoracallback__TConnectionInfo_Closure)
                 (const Agoracallback__TConnectionInfo *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor agoracallback__tconnection_info__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_callback_2eproto__INCLUDED */
